//
// Created by mamr5 on 28/06/2026.
//

#ifndef COLLEGE_DATABASE_MANAGEMENT_PROGRAM_ATTEMPT_H
#define COLLEGE_DATABASE_MANAGEMENT_PROGRAM_ATTEMPT_H


class Attempt
{
};


#endif //COLLEGE_DATABASE_MANAGEMENT_PROGRAM_ATTEMPT_H
