//
// Created by mamr5 on 28/06/2026.
//

#ifndef COLLEGE_DATABASE_MANAGEMENT_PROGRAM_COURSES_H
#define COLLEGE_DATABASE_MANAGEMENT_PROGRAM_COURSES_H


class Courses
{
};


#endif //COLLEGE_DATABASE_MANAGEMENT_PROGRAM_COURSES_H
