//
// Created by mamr5 on 28/06/2026.
//

#ifndef COLLEGE_DATABASE_MANAGEMENT_PROGRAM_DEPARTMENTS_H
#define COLLEGE_DATABASE_MANAGEMENT_PROGRAM_DEPARTMENTS_H


class Departments
{
};


#endif //COLLEGE_DATABASE_MANAGEMENT_PROGRAM_DEPARTMENTS_H
