//
// Created by mamr5 on 28/06/2026.
//

#ifndef COLLEGE_DATABASE_MANAGEMENT_PROGRAM_ENROLLMENT_H
#define COLLEGE_DATABASE_MANAGEMENT_PROGRAM_ENROLLMENT_H


class Enrollment
{
};


#endif //COLLEGE_DATABASE_MANAGEMENT_PROGRAM_ENROLLMENT_H
