//
// Created by mamr5 on 28/06/2026.
//

#ifndef COLLEGE_DATABASE_MANAGEMENT_PROGRAM_EXAMS_H
#define COLLEGE_DATABASE_MANAGEMENT_PROGRAM_EXAMS_H


class Exams
{
};


#endif //COLLEGE_DATABASE_MANAGEMENT_PROGRAM_EXAMS_H
