//
// Created by mamr5 on 28/06/2026.
//

#ifndef COLLEGE_DATABASE_MANAGEMENT_PROGRAM_STUDENTS_H
#define COLLEGE_DATABASE_MANAGEMENT_PROGRAM_STUDENTS_H


class Students
{
};


#endif //COLLEGE_DATABASE_MANAGEMENT_PROGRAM_STUDENTS_H
